= guppy4j / web

Pure Java web framework

== Releases

No releases yet. 
This project is in alpha status.

== Build status

image:https://travis-ci.org/guppy4j/web.svg?branch=master[
link="https://travis-ci.org/guppy4j/web"]

== Requirements

x  Allow MVC and component style web development in pure Java +
x  No HTML, CSS, JSP, XML or properties files +
x  Provide libraries for pure Java representation of HTML and CSS + 
x  Templating in Java (methods, inheritance, parametrization) +
x  Validation as part of the domain model classes +
x  Limit the use of annotations and reflection +
x  Localization using L10n registry, lookup in Java +
x  Page navigation rules in pure Java +
x  Pluggable URL routing (with resource based approach as default) +
x  Transparent conversion of HTTP params to model objects +
x  Deployable as WAR to standard web containers like Tomcat +
x  Use interfaces and immutable objects wherever possible +
x  TBD: JavaScript / Ajax support +

== Related libraries/frameworks

Projects I am reviewing for ideas:

Grab method name of MethodReference using proxies (for chained method handles that keep track of method path): +
- http://benjiweber.co.uk/blog/2013/12/28/typesafe-database-interaction-with-java-8/ +

For RESTful approach and readable API (but not the JSP part): +
- https://github.com/caelum/vraptor +

For some ideas around HTML generation in pure Java (DSL): + 
- https://github.com/luiz/vraptor-html-dsl +
- http://code.google.com/p/jatl/ +
- https://github.com/emicklei/rendersnake +
- http://docs.oracle.com/javase/8/docs/api/javax/swing/text/html/package-summary.html +

For some ideas around CSS representation in pure Java: +
- https://github.com/corgrath/Java-CSS-Library +
- https://code.google.com/p/phloc-css/ +

For how complex pure Java templating is in JSF: +
- http://java.dzone.com/articles/creating-jsf-pages-pure-java +
