= guppy4j / web

Pure Java web framework

== Releases

No releases yet. 
This project is in alpha status.

== Build status

image:https://travis-ci.org/guppy4j/web.svg?branch=master[
link="https://travis-ci.org/guppy4j/web"]

== Requirements

o-  Allow MVC and component style web development in pure Java +
o-  No HTML, CSS, JSP, XML or properties files +
o-  Provide libraries for pure Java representation of HTML and CSS + 
o-  Templating in Java (methods, inheritance, parametrization) +
o-  Validation as part of the domain model classes +
o-  Limit the use of annotations and reflection +
o-  Use interfaces and immutable objects wherever possible +
o-  Localization using L10n registry, lookup in Java +
o-  Page navigation rules in pure Java +
o-  Pluggable URL routing (with resource based approach as default) +
o-  Transparent conversion of HTTP params to model objects +
o-  By default each "webapp" runs in separate JVM using embedded HTTP engine +
o-  Utilize a high performance HTTP engine like Undertow +
o-  Future: Deployable as WAR to standard web containers like Tomcat +
o-  TBD: JavaScript / Ajax support +

== Related libraries/frameworks

Projects I review for ideas:

Grab method name of MethodReference using proxies (for chained method handles that keep track of method path): +
- http://benjiweber.co.uk/blog/2013/12/28/typesafe-database-interaction-with-java-8/ +

For RESTful approach and readable API (but not the JSP part): +
- https://github.com/caelum/vraptor +

For some ideas around HTML generation in pure Java (DSL): + 
- https://github.com/luiz/vraptor-html-dsl +
- http://code.google.com/p/jatl/ +
- https://github.com/emicklei/rendersnake +
- http://docs.oracle.com/javase/8/docs/api/javax/swing/text/html/package-summary.html +

For some ideas around CSS representation in pure Java: +
- https://github.com/corgrath/Java-CSS-Library +
- https://code.google.com/p/phloc-css/ +

For how complex pure Java templating is in JSF: +
- http://java.dzone.com/articles/creating-jsf-pages-pure-java +
